services:
  redmine:
    image: redmine:latest
    restart: always
    environment:
      REDMINE_DB_POSTGRES: db  # Correct service name for PostgreSQL
      REDMINE_DB_USERNAME: redmine_user
      REDMINE_DB_PASSWORD: redmine_pass
      REDMINE_DB_DATABASE: redmine_production
    ports:
      - "3000:3000"
    volumes:
      - redmine_data:/usr/src/redmine/files
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: redmine_production
      POSTGRES_USER: redmine_user
      POSTGRES_PASSWORD: redmine_pass
    volumes:
      - ./db:/var/lib/postgresql/data  # Bind mount to the local db directory

volumes:
  redmine_data:
